import { defineSchema, defineTable } from 'convex/server';
import { v } from 'convex/values';

export default defineSchema({
  cars: defineTable({
    make: v.string(),
    model: v.string(),
    year: v.number(),
    category: v.string(),
    dailyRate: v.number(),
    seats: v.number(),
    fuelType: v.string(),
    transmission: v.optional(v.string()),
    speed: v.string(),
    description: v.string(),
    image: v.string(),
    available: v.boolean(),
    featured: v.boolean(),
  }),

  users: defineTable({
    name: v.optional(v.string()),
    email: v.optional(v.string()),
    password: v.optional(v.string()),
    role: v.optional(v.string()),
    token: v.optional(v.string()),
    bio: v.optional(v.string()),
    phone: v.optional(v.string()),
    location: v.optional(v.string()),
    rating: v.optional(v.number()),
    reviewCount: v.optional(v.number()),
    roles: v.optional(v.array(v.string())),
    verified: v.optional(v.boolean()),
    kycStatus: v.optional(v.string()),
    theme: v.optional(v.string()),
    avatarUrl: v.optional(v.string()),
    createdAt: v.optional(v.number()),
  }).index('by_email', ['email']).index('by_token', ['token']),

  bookings: defineTable({
    userId: v.optional(v.id('users')),
    userName: v.optional(v.string()),
    userEmail: v.optional(v.string()),
    carId: v.optional(v.id('cars')),
    carMake: v.optional(v.string()),
    carModel: v.optional(v.string()),
    carImage: v.optional(v.string()),
    startDate: v.optional(v.union(v.string(), v.number())),
    endDate: v.optional(v.union(v.string(), v.number())),
    days: v.optional(v.number()),
    total: v.optional(v.union(v.number(), v.string())),
    dailyRate: v.optional(v.number()),
    status: v.optional(v.string()),
    paymentStatus: v.optional(v.string()),
    depositAmount: v.optional(v.number()),
    platformFee: v.optional(v.number()),
    totalAmount: v.optional(v.number()),
    guestId: v.optional(v.id('users')),
    hostId: v.optional(v.id('users')),
    mobileMoneyRef: v.optional(v.string()),
    checkInPhotos: v.optional(v.array(v.string())),
    checkOutPhotos: v.optional(v.array(v.string())),
    vehicleId: v.optional(v.string()),
    createdAt: v.optional(v.union(v.string(), v.number())),
    paidAt: v.optional(v.string()),
  })
    .index('by_userId', ['userId'])
    .index('by_status', ['status']),
});
